// Code generated by protoc-gen-go. DO NOT EDIT.
// source: prods.proto

package Models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProdModel struct {
	ProdID               int32    `protobuf:"varint,1,opt,name=ProdID,proto3" json:"ProdID,omitempty"`
	ProdName             string   `protobuf:"bytes,2,opt,name=ProdName,proto3" json:"ProdName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProdModel) Reset()         { *m = ProdModel{} }
func (m *ProdModel) String() string { return proto.CompactTextString(m) }
func (*ProdModel) ProtoMessage()    {}
func (*ProdModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfbbf742de0b26a4, []int{0}
}

func (m *ProdModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProdModel.Unmarshal(m, b)
}
func (m *ProdModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProdModel.Marshal(b, m, deterministic)
}
func (m *ProdModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProdModel.Merge(m, src)
}
func (m *ProdModel) XXX_Size() int {
	return xxx_messageInfo_ProdModel.Size(m)
}
func (m *ProdModel) XXX_DiscardUnknown() {
	xxx_messageInfo_ProdModel.DiscardUnknown(m)
}

var xxx_messageInfo_ProdModel proto.InternalMessageInfo

func (m *ProdModel) GetProdID() int32 {
	if m != nil {
		return m.ProdID
	}
	return 0
}

func (m *ProdModel) GetProdName() string {
	if m != nil {
		return m.ProdName
	}
	return ""
}

type ProdsReq struct {
	Size                 int32    `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProdsReq) Reset()         { *m = ProdsReq{} }
func (m *ProdsReq) String() string { return proto.CompactTextString(m) }
func (*ProdsReq) ProtoMessage()    {}
func (*ProdsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfbbf742de0b26a4, []int{1}
}

func (m *ProdsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProdsReq.Unmarshal(m, b)
}
func (m *ProdsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProdsReq.Marshal(b, m, deterministic)
}
func (m *ProdsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProdsReq.Merge(m, src)
}
func (m *ProdsReq) XXX_Size() int {
	return xxx_messageInfo_ProdsReq.Size(m)
}
func (m *ProdsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ProdsReq.DiscardUnknown(m)
}

var xxx_messageInfo_ProdsReq proto.InternalMessageInfo

func (m *ProdsReq) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type ProdListResp struct {
	Data                 []*ProdModel `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ProdListResp) Reset()         { *m = ProdListResp{} }
func (m *ProdListResp) String() string { return proto.CompactTextString(m) }
func (*ProdListResp) ProtoMessage()    {}
func (*ProdListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfbbf742de0b26a4, []int{2}
}

func (m *ProdListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProdListResp.Unmarshal(m, b)
}
func (m *ProdListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProdListResp.Marshal(b, m, deterministic)
}
func (m *ProdListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProdListResp.Merge(m, src)
}
func (m *ProdListResp) XXX_Size() int {
	return xxx_messageInfo_ProdListResp.Size(m)
}
func (m *ProdListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ProdListResp.DiscardUnknown(m)
}

var xxx_messageInfo_ProdListResp proto.InternalMessageInfo

func (m *ProdListResp) GetData() []*ProdModel {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ProdModel)(nil), "Models.ProdModel")
	proto.RegisterType((*ProdsReq)(nil), "Models.ProdsReq")
	proto.RegisterType((*ProdListResp)(nil), "Models.ProdListResp")
}

func init() {
	proto.RegisterFile("prods.proto", fileDescriptor_cfbbf742de0b26a4)
}

var fileDescriptor_cfbbf742de0b26a4 = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x28, 0xca, 0x4f,
	0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xf3, 0xcd, 0x4f, 0x49, 0xcd, 0x29, 0x56,
	0xb2, 0xe7, 0xe2, 0x0c, 0x28, 0xca, 0x4f, 0x01, 0xf3, 0x84, 0xc4, 0xb8, 0xd8, 0x40, 0x1c, 0x4f,
	0x17, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x28, 0x4f, 0x48, 0x8a, 0x8b, 0x03, 0xc4, 0xf2,
	0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf3, 0x95, 0xe4, 0x20, 0x72,
	0xc5, 0x41, 0xa9, 0x85, 0x42, 0x42, 0x5c, 0x2c, 0xc5, 0x99, 0x55, 0xa9, 0x50, 0xdd, 0x60, 0xb6,
	0x92, 0x29, 0x17, 0x0f, 0x48, 0xde, 0x27, 0xb3, 0xb8, 0x24, 0x28, 0xb5, 0xb8, 0x40, 0x48, 0x95,
	0x8b, 0x25, 0x25, 0xb1, 0x24, 0x51, 0x82, 0x51, 0x81, 0x59, 0x83, 0xdb, 0x48, 0x50, 0x0f, 0xe2,
	0x0e, 0x3d, 0xb8, 0x23, 0x82, 0xc0, 0xd2, 0x49, 0x6c, 0x60, 0x67, 0x1a, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xeb, 0x91, 0x6a, 0x4b, 0xb5, 0x00, 0x00, 0x00,
}
