// Code generated by protoc-gen-go. DO NOT EDIT.
// source: prodService.proto

package Service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProdsReq struct {
	// @inject_tag: json:"size", form:"size"
	Size int32 `protobuf:"varint,1,opt,name=size,proto3" json:"size" form:"size"`
	// @inject_tag: uri:"pid"
	ProdId               int32    `protobuf:"varint,2,opt,name=prod_id,json=prodId,proto3" json:"prod_id,omitempty" uri:"pid"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProdsReq) Reset()         { *m = ProdsReq{} }
func (m *ProdsReq) String() string { return proto.CompactTextString(m) }
func (*ProdsReq) ProtoMessage()    {}
func (*ProdsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_004a5da367890093, []int{0}
}

func (m *ProdsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProdsReq.Unmarshal(m, b)
}
func (m *ProdsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProdsReq.Marshal(b, m, deterministic)
}
func (m *ProdsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProdsReq.Merge(m, src)
}
func (m *ProdsReq) XXX_Size() int {
	return xxx_messageInfo_ProdsReq.Size(m)
}
func (m *ProdsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ProdsReq.DiscardUnknown(m)
}

var xxx_messageInfo_ProdsReq proto.InternalMessageInfo

func (m *ProdsReq) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ProdsReq) GetProdId() int32 {
	if m != nil {
		return m.ProdId
	}
	return 0
}

type ProdListResp struct {
	Data                 []*ProdModel `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ProdListResp) Reset()         { *m = ProdListResp{} }
func (m *ProdListResp) String() string { return proto.CompactTextString(m) }
func (*ProdListResp) ProtoMessage()    {}
func (*ProdListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_004a5da367890093, []int{1}
}

func (m *ProdListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProdListResp.Unmarshal(m, b)
}
func (m *ProdListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProdListResp.Marshal(b, m, deterministic)
}
func (m *ProdListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProdListResp.Merge(m, src)
}
func (m *ProdListResp) XXX_Size() int {
	return xxx_messageInfo_ProdListResp.Size(m)
}
func (m *ProdListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ProdListResp.DiscardUnknown(m)
}

var xxx_messageInfo_ProdListResp proto.InternalMessageInfo

func (m *ProdListResp) GetData() []*ProdModel {
	if m != nil {
		return m.Data
	}
	return nil
}

type ProdDetailtResp struct {
	Data                 *ProdModel `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProdDetailtResp) Reset()         { *m = ProdDetailtResp{} }
func (m *ProdDetailtResp) String() string { return proto.CompactTextString(m) }
func (*ProdDetailtResp) ProtoMessage()    {}
func (*ProdDetailtResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_004a5da367890093, []int{2}
}

func (m *ProdDetailtResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProdDetailtResp.Unmarshal(m, b)
}
func (m *ProdDetailtResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProdDetailtResp.Marshal(b, m, deterministic)
}
func (m *ProdDetailtResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProdDetailtResp.Merge(m, src)
}
func (m *ProdDetailtResp) XXX_Size() int {
	return xxx_messageInfo_ProdDetailtResp.Size(m)
}
func (m *ProdDetailtResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ProdDetailtResp.DiscardUnknown(m)
}

var xxx_messageInfo_ProdDetailtResp proto.InternalMessageInfo

func (m *ProdDetailtResp) GetData() *ProdModel {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ProdsReq)(nil), "Service.ProdsReq")
	proto.RegisterType((*ProdListResp)(nil), "Service.ProdListResp")
	proto.RegisterType((*ProdDetailtResp)(nil), "Service.ProdDetailtResp")
}

func init() {
	proto.RegisterFile("prodService.proto", fileDescriptor_004a5da367890093)
}

var fileDescriptor_004a5da367890093 = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0xca, 0x4f,
	0x09, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87,
	0x72, 0xa5, 0x78, 0x72, 0xf3, 0x53, 0x52, 0x73, 0x8a, 0x21, 0xc2, 0x4a, 0xe6, 0x5c, 0x1c, 0x01,
	0x45, 0xf9, 0x29, 0xc5, 0x41, 0xa9, 0x85, 0x42, 0x42, 0x5c, 0x2c, 0xc5, 0x99, 0x55, 0xa9, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x60, 0xb6, 0x90, 0x38, 0x17, 0x3b, 0xc8, 0xac, 0xf8, 0xcc,
	0x14, 0x09, 0x26, 0xb0, 0x30, 0x1b, 0x88, 0xeb, 0x99, 0xa2, 0x64, 0xc6, 0xc5, 0x03, 0xd2, 0xe8,
	0x93, 0x59, 0x5c, 0x12, 0x94, 0x5a, 0x5c, 0x20, 0xa4, 0xc6, 0xc5, 0x92, 0x92, 0x58, 0x92, 0x28,
	0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0x6d, 0x24, 0xa4, 0x07, 0xb3, 0x1d, 0xa4, 0xc8, 0x17, 0x64, 0x63,
	0x10, 0x58, 0x5e, 0xc9, 0x92, 0x8b, 0x1f, 0x24, 0xe4, 0x92, 0x5a, 0x92, 0x98, 0x99, 0x83, 0xae,
	0x95, 0x11, 0x9f, 0x56, 0xa3, 0x36, 0x46, 0x2e, 0xee, 0x00, 0x84, 0xc7, 0x84, 0x2c, 0xb8, 0x78,
	0xdc, 0x53, 0x4b, 0xc0, 0xce, 0x07, 0x39, 0x43, 0x48, 0x10, 0x45, 0x27, 0xc8, 0x4b, 0x52, 0xa2,
	0x28, 0x42, 0x70, 0xc7, 0xda, 0x72, 0xf1, 0xc1, 0x74, 0x42, 0x1c, 0x82, 0x4d, 0xaf, 0x04, 0x8a,
	0x10, 0x92, 0x83, 0x93, 0xd8, 0xc0, 0x61, 0x67, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x65, 0xf8,
	0x95, 0x66, 0x67, 0x01, 0x00, 0x00,
}
